### ISSUE TITLE
Error: Unexpected token export

### ISSUE THREAD

**Issue by ndabAP** [xlsdg/vue-countup-v2#20]
> SyntaxError: Unexpected token export
>     at Module._compile (internal/modules/cjs/loader.js:760:23)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
>     at Module.load (internal/modules/cjs/loader.js:685:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:620:12)
>     at Module.require (internal/modules/cjs/loader.js:723:19)
>     at require (internal/modules/cjs/helpers.js:14:16)
>     at Object.<anonymous> (/home/jvawcj/Coding/better-hr/betterhr-portal/node_modules/vue-countup-v2/dist/countup.min.js:1:29)
>     at Module._compile (internal/modules/cjs/loader.js:816:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
>     at Module.load (internal/modules/cjs/loader.js:685:32)

Using gridsome.

**Comment by ndabAP** [comment]
Its gridsomes fault. Solved it with relative import:

`import ICountUp from '../node_modules/vue-countup-v2'`
